version: '3'
services:
    db: 
        image: postgres
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Cosonic56

    api:
        build: ./api
        ports:
            - "4001:4001"
        depends_on:
            - db
        environment:
            DB_HOST: db

    web:
        build: ./web-app
        ports:
            - "3001:3000"
        depends_on:
            - api
        environment:
            # TODO: Change this to the server name
            # REACT_APP_SERVER_NAME: http://localhost
            REACT_APP_SERVER_PORT: 4001
volumes:
    db_data: